# -*- coding: utf-8 -*-
"""Actividad2_A01739421.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11mfyIq-sgqvnA4zcaObaMID8qw2fvsqU
"""

import pandas as pd

df = pd.DataFrame({
    'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana',
                'Beans', 'Orange', 'Broccoli', 'Banana'],
    'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
    'Amount': [270, 239, 617, 384, 626, 610, 62, 90]
})

print(df)

print(df[['Product', 'Quantity']])

print(df.loc[[4, 6]])

print(df.groupby('Product')['Quantity'].sum())

print(df.groupby('Category')['Amount'].sum())